id: P000814
initial_creation_type: ocr
created_at: 5/04/2021
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1PD104698
  title: གྲོ་ལུང་པ་བློ་གྲོས་འབྱུང་གནས་ཀྱི་གསུང་ཆོས་སྐོར
  volumes:
    63811923f113456c8e423d8d6a90f613:
      image_group_id: I1KG5853
      title: ''
      base_file: v001.txt
    b080717fd5e44aaf88ec398bed3e7259:
      image_group_id: I1KG5854
      title: ''
      base_file: v002.txt
  author: ''
